### ISSUE TITLE
Unexpected output using pretrained weights on custom preprocessed data

### ISSUE THREAD

**Issue by Fjr9516** [LemuelPuglisi/BrLP#2]
First of all, thank you for open-sourcing this wonderful work! It’s exciting to explore its application to my data.

I encountered an issue while trying to use the pretrained weights on my data. Since my preprocessing steps are slightly different, I suspect that this might have contributed to the unexpected results. I would greatly appreciate any guidance or suggestions to resolve this.

### 1. Preprocessing
- The T1w scan was processed using **Freesurfer** (FS), which included skull-stripping and bias correction.
- The scan was then registered and resampled into FS Talairach space (MNI305).
- Intensities were scaled between 0 and 1.
- Background regions were cropped, resulting in images of shape **160x176x208**.

### 2. Segmentation
- Segmentation masks were generated using **SynthSeg 2.0**.

### 3. CSV Input Preparation
I prepared the input CSV file as follows:

| subject_id | image_uid | age | sex | image_path                      | segm_path                          |
|------------|-----------|-----|-----|---------------------------------|------------------------------------|
| ID          | UID      | 51 | 0.0  | /path_to_my_data/img.nii.gz    | /path_to_my_data/img_SynthSeg.nii.gz |

### 4. Command Executed
I ran the following command:
`brlp --input ./examples/input.mydata.csv --output ./examples/Outputs.mydata/ --confs ./examples/confs.example.yaml --target_age 53 --target_diagnosis 1 --steps 2`

### 5. Visualization
Below are screenshots of the input image and segmentation, visualized in Freeview:
- Input Image:
![image](https://github.com/user-attachments/assets/d2c5cfac-aee6-4369-8bbb-891cd893c419)
- Segmentation:
![image](https://github.com/user-attachments/assets/bed87098-a478-426d-b5e2-d064bc738092)

### 6. Output
Here is the output (followup_age_53.nii.gz) I obtained after running `brlp`:
![image](https://github.com/user-attachments/assets/2f8c7646-9a8e-405d-9fa5-e54262d17a44)

I’d be grateful for any suggestions or advice to help me get the expected results. Thank you again for making this excellent tool available! 🙏

**Comment by LemuelPuglisi** [comment]
PS: here's a [link](https://github.com/Washington-University/HCPpipelines/blob/master/global/templates/MNI152_T1_1mm_brain.nii.gz) for the MNI125 template! You should provide this template as the third argument of `turboprep`.

**Comment by LemuelPuglisi** [comment]
Hi Jingru,

Awesome! It seems to be working :).

We trained BrLP's autoencoder using MRI scans at a $1.5\text{mm}^3$ resolution, which makes the output blurrier compared to the input MRI, which is probably at a $1\text{mm}^3$ resolution. The output appears bright because we apply an intensity normalisation in this line of code:

https://github.com/LemuelPuglisi/BrLP/blob/e9b533c877ed23e3d3ece010ef5a0a91c0736070/src/brlp/cli.py#L144

Regarding the progression, we are observing normal ageing and expect a slower atrophy process. Could you try setting an older target age, such as 85–90 years old?

I'm really curious to see the results!
